### ISSUE TITLE
bug: Submenu items are not accessible on mobile 

### ISSUE THREAD

**Issue by ssssoz** [WomenCodingCommunity/WomenCodingCommunity.github.io#143] opened 2024-05-01 07:36 UTC
### Describe the bug

Tapping on any menu item on mobile to reveal its subitems leads users to the top-level page and doesn’t give them the opportunity to browse or access any secondary pages. 

### To Reproduce

1. On mobile, go to https://womencodingcommunity.com/ 
2. Tap the hamburger menu 
3. Tap any menus that contain submenus (Mentorship, About Us)
   - Outlier here: Programmes works fine and effectively shows the submenu items since there’s no top-level link on the menu title (Programmes) 
4. See that they'll lead to the top-level page, and that the submenus —containing, for example, Mentors / Resources / Code of Conduct / FAQ— appear quickly and can’t be accessed. 

### Expected behavior

User should tap on top-level menu items without navigating to the page. User should be able to access sub-menu items by tapping instead. 

### Screenshots

![WhatsApp Video 2024-05-01 at 09 41 18](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/6668406/8fb90098-e7f4-41c0-890e-e9370ec5fcbe)

### Smartphone (please complete the following information):
 - Device: Google Pixel 6
 - OS: Android 14
 - Browser: Chrome 124.0.6367.82

### Reproducibility
- [x] The bug is reproducible consistently.
- [ ] The bug is sporadic or occurs randomly.

### Impact
- [x] The bug affects critical functionality.
- [ ] The bug affects minor functionality.
- [ ] The bug is a cosmetic issue.

### Related Issues/PRs

- Possibly occurred after changing from menu items being shown on hover instead of clicking/tapping in https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/pull/107 
- Could be paired with the #139 a11y fix

### Proposed Solution (optional)

- Only allow showing menu items on hover on desktop 
- Not using top-level menu item as a link and only include them as a submenu item (as with Programmes)

**Comment by lilyndk** [comment] 2024-05-01 10:03
Closing issue as a duplicate of https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/115

**Closed as completed by lilyndk** 2024-05-01 10:03 UTC
